# Generated by Django 4.0 on 2022-11-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bridge',
            },
        ),
        migrations.CreateModel(
            name='GetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsondata', models.TextField()),
            ],
            options={
                'db_table': 'getdata',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1000)),
                ('menu_name', models.CharField(max_length=200, unique=True)),
                ('menu_image', models.ImageField(default='default.png', upload_to='kiosk')),
                ('price', models.IntegerField()),
                ('explain', models.CharField(default='None', max_length=400)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('menu_list', models.TextField()),
                ('all_price', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('is_new', models.BooleanField(default=True)),
                ('take_out', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-create_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_list', models.CharField(max_length=500)),
                ('priority', models.IntegerField(default=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.menu')),
            ],
            options={
                'db_table': 'option',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('priority', models.IntegerField(default=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
                ('menu_set', models.ManyToManyField(through='webKiosk.Bridge', to='webKiosk.Menu')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.category'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.menu'),
        ),
    ]
