# Generated by Django 4.0 on 2022-11-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('priority', models.IntegerField(default=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1000)),
                ('menu_name', models.CharField(max_length=200, unique=True)),
                ('menu_image', models.ImageField(default='default.png', upload_to='kiosk')),
                ('price', models.IntegerField()),
                ('explain', models.CharField(default='None', max_length=400)),
                ('is_forbidden', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('table_num', models.IntegerField(default=0)),
                ('order_num', models.IntegerField(default=0)),
                ('menu_list', models.TextField()),
                ('all_price', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('is_new', models.BooleanField(default=True)),
                ('take_out', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-create_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=200)),
                ('option_list', models.CharField(max_length=500)),
                ('priority', models.IntegerField(default=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
            ],
            options={
                'db_table': 'option',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.menu')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.option')),
            ],
            options={
                'db_table': 'opme',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='option',
            field=models.ManyToManyField(through='webKiosk.Opme', to='webKiosk.Option'),
        ),
        migrations.CreateModel(
            name='Meca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webKiosk.menu')),
            ],
            options={
                'db_table': 'meca',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu_set',
            field=models.ManyToManyField(through='webKiosk.Meca', to='webKiosk.Menu'),
        ),
    ]
