# Generated by Django 4.0 on 2022-11-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=200),
        ),
    ]
