# Generated by Django 4.0 on 2022-11-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetData',
        ),
    ]
