# Generated by Django 4.0 on 2022-11-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0002_alter_option_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
