# Generated by Django 4.0 on 2022-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0004_alter_menu_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='market_name',
            field=models.CharField(default='S', max_length=200),
        ),
    ]
