# Generated by Django 4.0 on 2022-11-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='option',
            new_name='option_set',
        ),
    ]
