# Generated by Django 4.0 on 2022-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=200),
        ),
    ]
