# Generated by Django 4.0 on 2022-11-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webKiosk', '0005_option_market_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='market_name',
            field=models.CharField(max_length=200),
        ),
    ]
