# Generated by Django 4.1 on 2022-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webKiosk", "0006_alter_option_market_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="max_table",
            field=models.IntegerField(default=0),
        ),
    ]
